/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.tables.records


import er.codes.saltyvote.jooq.tables.LocalPictureStore

import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class LocalPictureStoreRecord() : UpdatableRecordImpl<LocalPictureStoreRecord>(LocalPictureStore.LOCAL_PICTURE_STORE) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var localPath: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(2, value)
        get(): OffsetDateTime? = get(2) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised LocalPictureStoreRecord
     */
    constructor(id: Long? = null, localPath: String? = null, createdAt: OffsetDateTime? = null): this() {
        this.id = id
        this.localPath = localPath
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised LocalPictureStoreRecord
     */
    constructor(value: er.codes.saltyvote.jooq.tables.pojos.LocalPictureStore?): this() {
        if (value != null) {
            this.id = value.id
            this.localPath = value.localPath
            this.createdAt = value.createdAt
            resetTouchedOnNotNull()
        }
    }
}
