/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.tables.records


import er.codes.saltyvote.jooq.tables.VoteOptions

import java.time.OffsetDateTime

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class VoteOptionsRecord() : UpdatableRecordImpl<VoteOptionsRecord>(VoteOptions.VOTE_OPTIONS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var voteId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var label: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var `data`: JSONB?
        set(value): Unit = set(3, value)
        get(): JSONB? = get(3) as JSONB?

    open var position: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised VoteOptionsRecord
     */
    constructor(id: Long? = null, voteId: Long? = null, label: String? = null, `data`: JSONB? = null, position: Int? = null, createdAt: OffsetDateTime? = null): this() {
        this.id = id
        this.voteId = voteId
        this.label = label
        this.`data` = `data`
        this.position = position
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised VoteOptionsRecord
     */
    constructor(value: er.codes.saltyvote.jooq.tables.pojos.VoteOptions?): this() {
        if (value != null) {
            this.id = value.id
            this.voteId = value.voteId
            this.label = value.label
            this.`data` = value.`data`
            this.position = value.position
            this.createdAt = value.createdAt
            resetTouchedOnNotNull()
        }
    }
}
