/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.tables.records


import er.codes.saltyvote.jooq.tables.VoteOptionExternalData

import java.math.BigDecimal
import java.time.OffsetDateTime

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class VoteOptionExternalDataRecord() : UpdatableRecordImpl<VoteOptionExternalDataRecord>(VoteOptionExternalData.VOTE_OPTION_EXTERNAL_DATA) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var voteOptionId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var sourceUrl: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var airbnbTitle: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var airbnbReviewCount: BigDecimal?
        set(value): Unit = set(4, value)
        get(): BigDecimal? = get(4) as BigDecimal?

    open var airbnbStarRating: BigDecimal?
        set(value): Unit = set(5, value)
        get(): BigDecimal? = get(5) as BigDecimal?

    open var airbnbPictureUrl: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var airbnbPictureLocalId: Long?
        set(value): Unit = set(7, value)
        get(): Long? = get(7) as Long?

    open var rawPayload: JSONB?
        set(value): Unit = set(8, value)
        get(): JSONB? = get(8) as JSONB?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(9, value)
        get(): OffsetDateTime? = get(9) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised VoteOptionExternalDataRecord
     */
    constructor(id: Long? = null, voteOptionId: Long? = null, sourceUrl: String? = null, airbnbTitle: String? = null, airbnbReviewCount: BigDecimal? = null, airbnbStarRating: BigDecimal? = null, airbnbPictureUrl: String? = null, airbnbPictureLocalId: Long? = null, rawPayload: JSONB? = null, createdAt: OffsetDateTime? = null): this() {
        this.id = id
        this.voteOptionId = voteOptionId
        this.sourceUrl = sourceUrl
        this.airbnbTitle = airbnbTitle
        this.airbnbReviewCount = airbnbReviewCount
        this.airbnbStarRating = airbnbStarRating
        this.airbnbPictureUrl = airbnbPictureUrl
        this.airbnbPictureLocalId = airbnbPictureLocalId
        this.rawPayload = rawPayload
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised VoteOptionExternalDataRecord
     */
    constructor(value: er.codes.saltyvote.jooq.tables.pojos.VoteOptionExternalData?): this() {
        if (value != null) {
            this.id = value.id
            this.voteOptionId = value.voteOptionId
            this.sourceUrl = value.sourceUrl
            this.airbnbTitle = value.airbnbTitle
            this.airbnbReviewCount = value.airbnbReviewCount
            this.airbnbStarRating = value.airbnbStarRating
            this.airbnbPictureUrl = value.airbnbPictureUrl
            this.airbnbPictureLocalId = value.airbnbPictureLocalId
            this.rawPayload = value.rawPayload
            this.createdAt = value.createdAt
            resetTouchedOnNotNull()
        }
    }
}
