/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.tables.daos


import er.codes.saltyvote.jooq.AbstractSpringDAOImpl
import er.codes.saltyvote.jooq.enums.ActionType
import er.codes.saltyvote.jooq.tables.History
import er.codes.saltyvote.jooq.tables.records.HistoryRecord

import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.JSONB
import org.springframework.stereotype.Repository


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
@Repository
open class HistoryDao(configuration: Configuration?) : AbstractSpringDAOImpl<HistoryRecord, er.codes.saltyvote.jooq.tables.pojos.History, Long>(History.HISTORY, er.codes.saltyvote.jooq.tables.pojos.History::class.java, configuration) {

    /**
     * Create a new HistoryDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: er.codes.saltyvote.jooq.tables.pojos.History): Long? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long?, upperInclusive: Long?): List<er.codes.saltyvote.jooq.tables.pojos.History> = fetchRange(History.HISTORY.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<er.codes.saltyvote.jooq.tables.pojos.History> = fetch(History.HISTORY.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): er.codes.saltyvote.jooq.tables.pojos.History? = fetchOne(History.HISTORY.ID, value)

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCreatedAt(lowerInclusive: OffsetDateTime?, upperInclusive: OffsetDateTime?): List<er.codes.saltyvote.jooq.tables.pojos.History> = fetchRange(History.HISTORY.CREATED_AT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    fun fetchByCreatedAt(vararg values: OffsetDateTime): List<er.codes.saltyvote.jooq.tables.pojos.History> = fetch(History.HISTORY.CREATED_AT, *values)

    /**
     * Fetch records that have <code>action_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfActionType(lowerInclusive: ActionType?, upperInclusive: ActionType?): List<er.codes.saltyvote.jooq.tables.pojos.History> = fetchRange(History.HISTORY.ACTION_TYPE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>action_type IN (values)</code>
     */
    fun fetchByActionType(vararg values: ActionType): List<er.codes.saltyvote.jooq.tables.pojos.History> = fetch(History.HISTORY.ACTION_TYPE, *values)

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfUserId(lowerInclusive: UUID?, upperInclusive: UUID?): List<er.codes.saltyvote.jooq.tables.pojos.History> = fetchRange(History.HISTORY.USER_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    fun fetchByUserId(vararg values: UUID): List<er.codes.saltyvote.jooq.tables.pojos.History> = fetch(History.HISTORY.USER_ID, *values)

    /**
     * Fetch records that have <code>event_data BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfEventData(lowerInclusive: JSONB?, upperInclusive: JSONB?): List<er.codes.saltyvote.jooq.tables.pojos.History> = fetchRange(History.HISTORY.EVENT_DATA, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>event_data IN (values)</code>
     */
    fun fetchByEventData(vararg values: JSONB): List<er.codes.saltyvote.jooq.tables.pojos.History> = fetch(History.HISTORY.EVENT_DATA, *values)
}
