/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.tables.daos


import er.codes.saltyvote.jooq.AbstractSpringDAOImpl
import er.codes.saltyvote.jooq.tables.LocalPictureStore
import er.codes.saltyvote.jooq.tables.records.LocalPictureStoreRecord

import java.time.OffsetDateTime

import kotlin.collections.List

import org.jooq.Configuration
import org.springframework.stereotype.Repository


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
@Repository
open class LocalPictureStoreDao(configuration: Configuration?) : AbstractSpringDAOImpl<LocalPictureStoreRecord, er.codes.saltyvote.jooq.tables.pojos.LocalPictureStore, Long>(LocalPictureStore.LOCAL_PICTURE_STORE, er.codes.saltyvote.jooq.tables.pojos.LocalPictureStore::class.java, configuration) {

    /**
     * Create a new LocalPictureStoreDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: er.codes.saltyvote.jooq.tables.pojos.LocalPictureStore): Long? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long?, upperInclusive: Long?): List<er.codes.saltyvote.jooq.tables.pojos.LocalPictureStore> = fetchRange(LocalPictureStore.LOCAL_PICTURE_STORE.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<er.codes.saltyvote.jooq.tables.pojos.LocalPictureStore> = fetch(LocalPictureStore.LOCAL_PICTURE_STORE.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): er.codes.saltyvote.jooq.tables.pojos.LocalPictureStore? = fetchOne(LocalPictureStore.LOCAL_PICTURE_STORE.ID, value)

    /**
     * Fetch records that have <code>local_path BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfLocalPath(lowerInclusive: String?, upperInclusive: String?): List<er.codes.saltyvote.jooq.tables.pojos.LocalPictureStore> = fetchRange(LocalPictureStore.LOCAL_PICTURE_STORE.LOCAL_PATH, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>local_path IN (values)</code>
     */
    fun fetchByLocalPath(vararg values: String): List<er.codes.saltyvote.jooq.tables.pojos.LocalPictureStore> = fetch(LocalPictureStore.LOCAL_PICTURE_STORE.LOCAL_PATH, *values)

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCreatedAt(lowerInclusive: OffsetDateTime?, upperInclusive: OffsetDateTime?): List<er.codes.saltyvote.jooq.tables.pojos.LocalPictureStore> = fetchRange(LocalPictureStore.LOCAL_PICTURE_STORE.CREATED_AT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    fun fetchByCreatedAt(vararg values: OffsetDateTime): List<er.codes.saltyvote.jooq.tables.pojos.LocalPictureStore> = fetch(LocalPictureStore.LOCAL_PICTURE_STORE.CREATED_AT, *values)
}
