@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.tables.references


import er.codes.saltyvote.jooq.tables.History
import er.codes.saltyvote.jooq.tables.Users



/**
 * The table <code>public.history</code>.
 */
val HISTORY: History = History.HISTORY

/**
 * The table <code>public.users</code>.
 */
val USERS: Users = Users.USERS
