/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.tables.pojos


import er.codes.saltyvote.jooq.enums.ActionType

import java.io.Serializable
import java.time.OffsetDateTime
import java.util.UUID

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class History(
    var id: Long? = null,
    var createdAt: OffsetDateTime? = null,
    var actionType: ActionType? = null,
    var userId: UUID? = null,
    var eventData: JSONB? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: History = other as History
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.createdAt == null) {
            if (o.createdAt != null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.actionType == null) {
            if (o.actionType != null)
                return false
        }
        else if (this.actionType != o.actionType)
            return false
        if (this.userId == null) {
            if (o.userId != null)
                return false
        }
        else if (this.userId != o.userId)
            return false
        if (this.eventData == null) {
            if (o.eventData != null)
                return false
        }
        else if (this.eventData != o.eventData)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.createdAt == null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.actionType == null) 0 else this.actionType.hashCode())
        result = prime * result + (if (this.userId == null) 0 else this.userId.hashCode())
        result = prime * result + (if (this.eventData == null) 0 else this.eventData.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("History (")

        sb.append(id)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(actionType)
        sb.append(", ").append(userId)
        sb.append(", ").append(eventData)

        sb.append(")")
        return sb.toString()
    }
}
