/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.tables.pojos


import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class LocalPictureStore(
    var id: Long? = null,
    var localPath: String? = null,
    var createdAt: OffsetDateTime? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: LocalPictureStore = other as LocalPictureStore
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.localPath == null) {
            if (o.localPath != null)
                return false
        }
        else if (this.localPath != o.localPath)
            return false
        if (this.createdAt == null) {
            if (o.createdAt != null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.localPath == null) 0 else this.localPath.hashCode())
        result = prime * result + (if (this.createdAt == null) 0 else this.createdAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("LocalPictureStore (")

        sb.append(id)
        sb.append(", ").append(localPath)
        sb.append(", ").append(createdAt)

        sb.append(")")
        return sb.toString()
    }
}
