/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.tables.pojos


import java.io.Serializable
import java.time.OffsetDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class Users(
    var uuid: UUID? = null,
    var email: String? = null,
    var username: String? = null,
    var password: String? = null,
    var admin: Boolean? = null,
    var enabled: Boolean? = null,
    var createdAt: OffsetDateTime? = null,
    var updatedAt: OffsetDateTime? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Users = other as Users
        if (this.uuid == null) {
            if (o.uuid != null)
                return false
        }
        else if (this.uuid != o.uuid)
            return false
        if (this.email == null) {
            if (o.email != null)
                return false
        }
        else if (this.email != o.email)
            return false
        if (this.username == null) {
            if (o.username != null)
                return false
        }
        else if (this.username != o.username)
            return false
        if (this.password == null) {
            if (o.password != null)
                return false
        }
        else if (this.password != o.password)
            return false
        if (this.admin == null) {
            if (o.admin != null)
                return false
        }
        else if (this.admin != o.admin)
            return false
        if (this.enabled == null) {
            if (o.enabled != null)
                return false
        }
        else if (this.enabled != o.enabled)
            return false
        if (this.createdAt == null) {
            if (o.createdAt != null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.updatedAt == null) {
            if (o.updatedAt != null)
                return false
        }
        else if (this.updatedAt != o.updatedAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.uuid == null) 0 else this.uuid.hashCode())
        result = prime * result + (if (this.email == null) 0 else this.email.hashCode())
        result = prime * result + (if (this.username == null) 0 else this.username.hashCode())
        result = prime * result + (if (this.password == null) 0 else this.password.hashCode())
        result = prime * result + (if (this.admin == null) 0 else this.admin.hashCode())
        result = prime * result + (if (this.enabled == null) 0 else this.enabled.hashCode())
        result = prime * result + (if (this.createdAt == null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.updatedAt == null) 0 else this.updatedAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Users (")

        sb.append(uuid)
        sb.append(", ").append(email)
        sb.append(", ").append(username)
        sb.append(", ").append(password)
        sb.append(", ").append(admin)
        sb.append(", ").append(enabled)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)

        sb.append(")")
        return sb.toString()
    }
}
