/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.tables.pojos


import java.io.Serializable
import java.math.BigDecimal
import java.time.OffsetDateTime

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class VoteOptionExternalData(
    var id: Long? = null,
    var voteOptionId: Long? = null,
    var sourceUrl: String? = null,
    var airbnbTitle: String? = null,
    var airbnbReviewCount: BigDecimal? = null,
    var airbnbStarRating: BigDecimal? = null,
    var airbnbPictureUrl: String? = null,
    var airbnbPictureLocalId: Long? = null,
    var rawPayload: JSONB? = null,
    var createdAt: OffsetDateTime? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: VoteOptionExternalData = other as VoteOptionExternalData
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.voteOptionId == null) {
            if (o.voteOptionId != null)
                return false
        }
        else if (this.voteOptionId != o.voteOptionId)
            return false
        if (this.sourceUrl == null) {
            if (o.sourceUrl != null)
                return false
        }
        else if (this.sourceUrl != o.sourceUrl)
            return false
        if (this.airbnbTitle == null) {
            if (o.airbnbTitle != null)
                return false
        }
        else if (this.airbnbTitle != o.airbnbTitle)
            return false
        if (this.airbnbReviewCount == null) {
            if (o.airbnbReviewCount != null)
                return false
        }
        else if (this.airbnbReviewCount != o.airbnbReviewCount)
            return false
        if (this.airbnbStarRating == null) {
            if (o.airbnbStarRating != null)
                return false
        }
        else if (this.airbnbStarRating != o.airbnbStarRating)
            return false
        if (this.airbnbPictureUrl == null) {
            if (o.airbnbPictureUrl != null)
                return false
        }
        else if (this.airbnbPictureUrl != o.airbnbPictureUrl)
            return false
        if (this.airbnbPictureLocalId == null) {
            if (o.airbnbPictureLocalId != null)
                return false
        }
        else if (this.airbnbPictureLocalId != o.airbnbPictureLocalId)
            return false
        if (this.rawPayload == null) {
            if (o.rawPayload != null)
                return false
        }
        else if (this.rawPayload != o.rawPayload)
            return false
        if (this.createdAt == null) {
            if (o.createdAt != null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.voteOptionId == null) 0 else this.voteOptionId.hashCode())
        result = prime * result + (if (this.sourceUrl == null) 0 else this.sourceUrl.hashCode())
        result = prime * result + (if (this.airbnbTitle == null) 0 else this.airbnbTitle.hashCode())
        result = prime * result + (if (this.airbnbReviewCount == null) 0 else this.airbnbReviewCount.hashCode())
        result = prime * result + (if (this.airbnbStarRating == null) 0 else this.airbnbStarRating.hashCode())
        result = prime * result + (if (this.airbnbPictureUrl == null) 0 else this.airbnbPictureUrl.hashCode())
        result = prime * result + (if (this.airbnbPictureLocalId == null) 0 else this.airbnbPictureLocalId.hashCode())
        result = prime * result + (if (this.rawPayload == null) 0 else this.rawPayload.hashCode())
        result = prime * result + (if (this.createdAt == null) 0 else this.createdAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("VoteOptionExternalData (")

        sb.append(id)
        sb.append(", ").append(voteOptionId)
        sb.append(", ").append(sourceUrl)
        sb.append(", ").append(airbnbTitle)
        sb.append(", ").append(airbnbReviewCount)
        sb.append(", ").append(airbnbStarRating)
        sb.append(", ").append(airbnbPictureUrl)
        sb.append(", ").append(airbnbPictureLocalId)
        sb.append(", ").append(rawPayload)
        sb.append(", ").append(createdAt)

        sb.append(")")
        return sb.toString()
    }
}
