/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class VoteSubmissionEntries(
    var id: Long? = null,
    var submissionId: Long? = null,
    var optionId: Long? = null,
    var rank: Int? = null,
    var selected: Boolean? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: VoteSubmissionEntries = other as VoteSubmissionEntries
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.submissionId == null) {
            if (o.submissionId != null)
                return false
        }
        else if (this.submissionId != o.submissionId)
            return false
        if (this.optionId == null) {
            if (o.optionId != null)
                return false
        }
        else if (this.optionId != o.optionId)
            return false
        if (this.rank == null) {
            if (o.rank != null)
                return false
        }
        else if (this.rank != o.rank)
            return false
        if (this.selected == null) {
            if (o.selected != null)
                return false
        }
        else if (this.selected != o.selected)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.submissionId == null) 0 else this.submissionId.hashCode())
        result = prime * result + (if (this.optionId == null) 0 else this.optionId.hashCode())
        result = prime * result + (if (this.rank == null) 0 else this.rank.hashCode())
        result = prime * result + (if (this.selected == null) 0 else this.selected.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("VoteSubmissionEntries (")

        sb.append(id)
        sb.append(", ").append(submissionId)
        sb.append(", ").append(optionId)
        sb.append(", ").append(rank)
        sb.append(", ").append(selected)

        sb.append(")")
        return sb.toString()
    }
}
