/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.tables.pojos


import java.io.Serializable
import java.time.OffsetDateTime

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class VoteOptions(
    var id: Long? = null,
    var voteId: Long? = null,
    var label: String? = null,
    var `data`: JSONB? = null,
    var createdAt: OffsetDateTime? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: VoteOptions = other as VoteOptions
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.voteId == null) {
            if (o.voteId != null)
                return false
        }
        else if (this.voteId != o.voteId)
            return false
        if (this.label == null) {
            if (o.label != null)
                return false
        }
        else if (this.label != o.label)
            return false
        if (this.`data` == null) {
            if (o.`data` != null)
                return false
        }
        else if (this.`data` != o.`data`)
            return false
        if (this.createdAt == null) {
            if (o.createdAt != null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.voteId == null) 0 else this.voteId.hashCode())
        result = prime * result + (if (this.label == null) 0 else this.label.hashCode())
        result = prime * result + (if (this.`data` == null) 0 else this.`data`.hashCode())
        result = prime * result + (if (this.createdAt == null) 0 else this.createdAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("VoteOptions (")

        sb.append(id)
        sb.append(", ").append(voteId)
        sb.append(", ").append(label)
        sb.append(", ").append(`data`)
        sb.append(", ").append(createdAt)

        sb.append(")")
        return sb.toString()
    }
}
