/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.tables.pojos


import java.io.Serializable
import java.time.OffsetDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class VoteCollaborators(
    var id: Long? = null,
    var voteId: Long? = null,
    var userId: UUID? = null,
    var createdAt: OffsetDateTime? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: VoteCollaborators = other as VoteCollaborators
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.voteId == null) {
            if (o.voteId != null)
                return false
        }
        else if (this.voteId != o.voteId)
            return false
        if (this.userId == null) {
            if (o.userId != null)
                return false
        }
        else if (this.userId != o.userId)
            return false
        if (this.createdAt == null) {
            if (o.createdAt != null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.voteId == null) 0 else this.voteId.hashCode())
        result = prime * result + (if (this.userId == null) 0 else this.userId.hashCode())
        result = prime * result + (if (this.createdAt == null) 0 else this.createdAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("VoteCollaborators (")

        sb.append(id)
        sb.append(", ").append(voteId)
        sb.append(", ").append(userId)
        sb.append(", ").append(createdAt)

        sb.append(")")
        return sb.toString()
    }
}
