entryPoints:
    web:
        address: ":80"
    websecure:
        address: ":443"

api:
    dashboard: true
    insecure: true

certificatesResolvers:
    letsencrypt:
        acme:
            email: denis@er.codes
            storage: /letsencrypt/acme.json
            httpChallenge:
                entryPoint: web

providers:
    file:
        filename: /etc/traefik/dynamic.yml
        watch: true
