/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.enums


import er.codes.saltyvote.jooq.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
enum class ActionType(@get:JvmName("literal") public val literal: String) : EnumType {
    LOBBY_CREATE("LOBBY_CREATE"),
    LOBBY_JOIN("LOBBY_JOIN"),
    LOBBY_CANCEL("LOBBY_CANCEL"),
    LOBBY_RESOLVE("LOBBY_RESOLVE"),
    USER_REGISTERED("USER_REGISTERED"),
    USER_LOGIN("USER_LOGIN"),
    USER_PASSWORD_CHANGED("USER_PASSWORD_CHANGED");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "action_type"
    override fun getLiteral(): String = literal
}
