/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.enums


import er.codes.saltyvote.jooq.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
enum class VoteType(@get:JvmName("literal") public val literal: String) : EnumType {
    RANKING("RANKING"),
    SIMPLE("SIMPLE");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "vote_type"
    override fun getLiteral(): String = literal
}
