@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.indexes


import er.codes.saltyvote.jooq.tables.VoteCollaborators

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_VOTE_COLLABORATORS_USER_ID: Index = Internal.createIndex(DSL.name("idx_vote_collaborators_user_id"), VoteCollaborators.VOTE_COLLABORATORS, arrayOf(VoteCollaborators.VOTE_COLLABORATORS.USER_ID), false)
val IDX_VOTE_COLLABORATORS_VOTE_ID: Index = Internal.createIndex(DSL.name("idx_vote_collaborators_vote_id"), VoteCollaborators.VOTE_COLLABORATORS, arrayOf(VoteCollaborators.VOTE_COLLABORATORS.VOTE_ID), false)
