/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.tables


import er.codes.saltyvote.jooq.Public
import er.codes.saltyvote.jooq.enums.ActionType
import er.codes.saltyvote.jooq.keys.HISTORY_PKEY
import er.codes.saltyvote.jooq.keys.HISTORY__HISTORY_USER_ID_FKEY
import er.codes.saltyvote.jooq.tables.Users.UsersPath
import er.codes.saltyvote.jooq.tables.records.HistoryRecord

import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class History(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, HistoryRecord>?,
    parentPath: InverseForeignKey<out Record, HistoryRecord>?,
    aliased: Table<HistoryRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<HistoryRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.history</code>
         */
        val HISTORY: History = History()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<HistoryRecord> = HistoryRecord::class.java

    /**
     * The column <code>public.history.id</code>.
     */
    val ID: TableField<HistoryRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.history.created_at</code>.
     */
    val CREATED_AT: TableField<HistoryRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.history.action_type</code>.
     */
    val ACTION_TYPE: TableField<HistoryRecord, ActionType?> = createField(DSL.name("action_type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(ActionType::class.java), this, "")

    /**
     * The column <code>public.history.user_id</code>.
     */
    val USER_ID: TableField<HistoryRecord, UUID?> = createField(DSL.name("user_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.history.event_data</code>.
     */
    val EVENT_DATA: TableField<HistoryRecord, JSONB?> = createField(DSL.name("event_data"), SQLDataType.JSONB, this, "")

    private constructor(alias: Name, aliased: Table<HistoryRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<HistoryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<HistoryRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.history</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.history</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.history</code> table reference
     */
    constructor(): this(DSL.name("history"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, HistoryRecord>?, parentPath: InverseForeignKey<out Record, HistoryRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, HISTORY, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class HistoryPath : History, Path<HistoryRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, HistoryRecord>?, parentPath: InverseForeignKey<out Record, HistoryRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<HistoryRecord>): super(alias, aliased)
        override fun `as`(alias: String): HistoryPath = HistoryPath(DSL.name(alias), this)
        override fun `as`(alias: Name): HistoryPath = HistoryPath(alias, this)
        override fun `as`(alias: Table<*>): HistoryPath = HistoryPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<HistoryRecord, Long?> = super.getIdentity() as Identity<HistoryRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<HistoryRecord> = HISTORY_PKEY
    override fun getReferences(): List<ForeignKey<HistoryRecord, *>> = listOf(HISTORY__HISTORY_USER_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    fun users(): UsersPath = users
    val users: UsersPath by lazy { UsersPath(this, HISTORY__HISTORY_USER_ID_FKEY, null) }
    override fun `as`(alias: String): History = History(DSL.name(alias), this)
    override fun `as`(alias: Name): History = History(alias, this)
    override fun `as`(alias: Table<*>): History = History(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): History = History(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): History = History(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): History = History(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): History = History(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): History = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): History = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): History = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): History = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): History = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): History = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): History = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): History = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): History = where(DSL.notExists(select))
}
