/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.tables


import er.codes.saltyvote.jooq.Public
import er.codes.saltyvote.jooq.keys.LOCAL_PICTURE_STORE_PKEY
import er.codes.saltyvote.jooq.keys.VOTE_OPTION_EXTERNAL_DATA__VOTE_OPTION_EXTERNAL_DATA_AIRBNB_PICTURE_LOCAL_ID_FKEY
import er.codes.saltyvote.jooq.tables.VoteOptionExternalData.VoteOptionExternalDataPath
import er.codes.saltyvote.jooq.tables.records.LocalPictureStoreRecord

import java.time.OffsetDateTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class LocalPictureStore(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, LocalPictureStoreRecord>?,
    parentPath: InverseForeignKey<out Record, LocalPictureStoreRecord>?,
    aliased: Table<LocalPictureStoreRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<LocalPictureStoreRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.local_picture_store</code>
         */
        val LOCAL_PICTURE_STORE: LocalPictureStore = LocalPictureStore()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<LocalPictureStoreRecord> = LocalPictureStoreRecord::class.java

    /**
     * The column <code>public.local_picture_store.id</code>.
     */
    val ID: TableField<LocalPictureStoreRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.local_picture_store.local_path</code>.
     */
    val LOCAL_PATH: TableField<LocalPictureStoreRecord, String?> = createField(DSL.name("local_path"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.local_picture_store.created_at</code>.
     */
    val CREATED_AT: TableField<LocalPictureStoreRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<LocalPictureStoreRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<LocalPictureStoreRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<LocalPictureStoreRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.local_picture_store</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.local_picture_store</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.local_picture_store</code> table reference
     */
    constructor(): this(DSL.name("local_picture_store"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, LocalPictureStoreRecord>?, parentPath: InverseForeignKey<out Record, LocalPictureStoreRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, LOCAL_PICTURE_STORE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class LocalPictureStorePath : LocalPictureStore, Path<LocalPictureStoreRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, LocalPictureStoreRecord>?, parentPath: InverseForeignKey<out Record, LocalPictureStoreRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<LocalPictureStoreRecord>): super(alias, aliased)
        override fun `as`(alias: String): LocalPictureStorePath = LocalPictureStorePath(DSL.name(alias), this)
        override fun `as`(alias: Name): LocalPictureStorePath = LocalPictureStorePath(alias, this)
        override fun `as`(alias: Table<*>): LocalPictureStorePath = LocalPictureStorePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<LocalPictureStoreRecord, Long?> = super.getIdentity() as Identity<LocalPictureStoreRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<LocalPictureStoreRecord> = LOCAL_PICTURE_STORE_PKEY

    private lateinit var _voteOptionExternalData: VoteOptionExternalDataPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.vote_option_external_data</code> table
     */
    fun voteOptionExternalData(): VoteOptionExternalDataPath {
        if (!this::_voteOptionExternalData.isInitialized)
            _voteOptionExternalData = VoteOptionExternalDataPath(this, null, VOTE_OPTION_EXTERNAL_DATA__VOTE_OPTION_EXTERNAL_DATA_AIRBNB_PICTURE_LOCAL_ID_FKEY.inverseKey)

        return _voteOptionExternalData;
    }

    val voteOptionExternalData: VoteOptionExternalDataPath
        get(): VoteOptionExternalDataPath = voteOptionExternalData()
    override fun `as`(alias: String): LocalPictureStore = LocalPictureStore(DSL.name(alias), this)
    override fun `as`(alias: Name): LocalPictureStore = LocalPictureStore(alias, this)
    override fun `as`(alias: Table<*>): LocalPictureStore = LocalPictureStore(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): LocalPictureStore = LocalPictureStore(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): LocalPictureStore = LocalPictureStore(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): LocalPictureStore = LocalPictureStore(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): LocalPictureStore = LocalPictureStore(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): LocalPictureStore = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): LocalPictureStore = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): LocalPictureStore = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): LocalPictureStore = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): LocalPictureStore = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): LocalPictureStore = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): LocalPictureStore = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): LocalPictureStore = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): LocalPictureStore = where(DSL.notExists(select))
}
