/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.tables


import er.codes.saltyvote.jooq.Public
import er.codes.saltyvote.jooq.indexes.IDX_VOTE_COLLABORATORS_USER_ID
import er.codes.saltyvote.jooq.indexes.IDX_VOTE_COLLABORATORS_VOTE_ID
import er.codes.saltyvote.jooq.keys.UQ_VOTE_COLLABORATOR
import er.codes.saltyvote.jooq.keys.VOTE_COLLABORATORS_PKEY
import er.codes.saltyvote.jooq.keys.VOTE_COLLABORATORS__VOTE_COLLABORATORS_USER_ID_FKEY
import er.codes.saltyvote.jooq.keys.VOTE_COLLABORATORS__VOTE_COLLABORATORS_VOTE_ID_FKEY
import er.codes.saltyvote.jooq.tables.Users.UsersPath
import er.codes.saltyvote.jooq.tables.Votes.VotesPath
import er.codes.saltyvote.jooq.tables.records.VoteCollaboratorsRecord

import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class VoteCollaborators(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, VoteCollaboratorsRecord>?,
    parentPath: InverseForeignKey<out Record, VoteCollaboratorsRecord>?,
    aliased: Table<VoteCollaboratorsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<VoteCollaboratorsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.vote_collaborators</code>
         */
        val VOTE_COLLABORATORS: VoteCollaborators = VoteCollaborators()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<VoteCollaboratorsRecord> = VoteCollaboratorsRecord::class.java

    /**
     * The column <code>public.vote_collaborators.id</code>.
     */
    val ID: TableField<VoteCollaboratorsRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.vote_collaborators.vote_id</code>.
     */
    val VOTE_ID: TableField<VoteCollaboratorsRecord, Long?> = createField(DSL.name("vote_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.vote_collaborators.user_id</code>.
     */
    val USER_ID: TableField<VoteCollaboratorsRecord, UUID?> = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.vote_collaborators.created_at</code>.
     */
    val CREATED_AT: TableField<VoteCollaboratorsRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<VoteCollaboratorsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<VoteCollaboratorsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<VoteCollaboratorsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.vote_collaborators</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.vote_collaborators</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.vote_collaborators</code> table reference
     */
    constructor(): this(DSL.name("vote_collaborators"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VoteCollaboratorsRecord>?, parentPath: InverseForeignKey<out Record, VoteCollaboratorsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, VOTE_COLLABORATORS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class VoteCollaboratorsPath : VoteCollaborators, Path<VoteCollaboratorsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VoteCollaboratorsRecord>?, parentPath: InverseForeignKey<out Record, VoteCollaboratorsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<VoteCollaboratorsRecord>): super(alias, aliased)
        override fun `as`(alias: String): VoteCollaboratorsPath = VoteCollaboratorsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): VoteCollaboratorsPath = VoteCollaboratorsPath(alias, this)
        override fun `as`(alias: Table<*>): VoteCollaboratorsPath = VoteCollaboratorsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_VOTE_COLLABORATORS_USER_ID, IDX_VOTE_COLLABORATORS_VOTE_ID)
    override fun getIdentity(): Identity<VoteCollaboratorsRecord, Long?> = super.getIdentity() as Identity<VoteCollaboratorsRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<VoteCollaboratorsRecord> = VOTE_COLLABORATORS_PKEY
    override fun getUniqueKeys(): List<UniqueKey<VoteCollaboratorsRecord>> = listOf(UQ_VOTE_COLLABORATOR)
    override fun getReferences(): List<ForeignKey<VoteCollaboratorsRecord, *>> = listOf(VOTE_COLLABORATORS__VOTE_COLLABORATORS_USER_ID_FKEY, VOTE_COLLABORATORS__VOTE_COLLABORATORS_VOTE_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    fun users(): UsersPath = users
    val users: UsersPath by lazy { UsersPath(this, VOTE_COLLABORATORS__VOTE_COLLABORATORS_USER_ID_FKEY, null) }

    /**
     * Get the implicit join path to the <code>public.votes</code> table.
     */
    fun votes(): VotesPath = votes
    val votes: VotesPath by lazy { VotesPath(this, VOTE_COLLABORATORS__VOTE_COLLABORATORS_VOTE_ID_FKEY, null) }
    override fun `as`(alias: String): VoteCollaborators = VoteCollaborators(DSL.name(alias), this)
    override fun `as`(alias: Name): VoteCollaborators = VoteCollaborators(alias, this)
    override fun `as`(alias: Table<*>): VoteCollaborators = VoteCollaborators(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): VoteCollaborators = VoteCollaborators(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): VoteCollaborators = VoteCollaborators(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): VoteCollaborators = VoteCollaborators(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): VoteCollaborators = VoteCollaborators(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): VoteCollaborators = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): VoteCollaborators = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): VoteCollaborators = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): VoteCollaborators = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): VoteCollaborators = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): VoteCollaborators = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): VoteCollaborators = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): VoteCollaborators = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): VoteCollaborators = where(DSL.notExists(select))
}
