/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.tables


import er.codes.saltyvote.jooq.Public
import er.codes.saltyvote.jooq.keys.VOTE_OPTIONS_PKEY
import er.codes.saltyvote.jooq.keys.VOTE_OPTIONS__VOTE_OPTIONS_VOTE_ID_FKEY
import er.codes.saltyvote.jooq.keys.VOTE_SUBMISSION_ENTRIES__VOTE_SUBMISSION_ENTRIES_OPTION_ID_FKEY
import er.codes.saltyvote.jooq.tables.VoteSubmissionEntries.VoteSubmissionEntriesPath
import er.codes.saltyvote.jooq.tables.VoteSubmissions.VoteSubmissionsPath
import er.codes.saltyvote.jooq.tables.Votes.VotesPath
import er.codes.saltyvote.jooq.tables.records.VoteOptionsRecord

import java.time.OffsetDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class VoteOptions(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, VoteOptionsRecord>?,
    parentPath: InverseForeignKey<out Record, VoteOptionsRecord>?,
    aliased: Table<VoteOptionsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<VoteOptionsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.vote_options</code>
         */
        val VOTE_OPTIONS: VoteOptions = VoteOptions()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<VoteOptionsRecord> = VoteOptionsRecord::class.java

    /**
     * The column <code>public.vote_options.id</code>.
     */
    val ID: TableField<VoteOptionsRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.vote_options.vote_id</code>.
     */
    val VOTE_ID: TableField<VoteOptionsRecord, Long?> = createField(DSL.name("vote_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.vote_options.label</code>.
     */
    val LABEL: TableField<VoteOptionsRecord, String?> = createField(DSL.name("label"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.vote_options.data</code>.
     */
    val DATA: TableField<VoteOptionsRecord, JSONB?> = createField(DSL.name("data"), SQLDataType.JSONB, this, "")

    /**
     * The column <code>public.vote_options.position</code>.
     */
    val POSITION: TableField<VoteOptionsRecord, Int?> = createField(DSL.name("position"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.vote_options.created_at</code>.
     */
    val CREATED_AT: TableField<VoteOptionsRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<VoteOptionsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<VoteOptionsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<VoteOptionsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.vote_options</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.vote_options</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.vote_options</code> table reference
     */
    constructor(): this(DSL.name("vote_options"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VoteOptionsRecord>?, parentPath: InverseForeignKey<out Record, VoteOptionsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, VOTE_OPTIONS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class VoteOptionsPath : VoteOptions, Path<VoteOptionsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VoteOptionsRecord>?, parentPath: InverseForeignKey<out Record, VoteOptionsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<VoteOptionsRecord>): super(alias, aliased)
        override fun `as`(alias: String): VoteOptionsPath = VoteOptionsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): VoteOptionsPath = VoteOptionsPath(alias, this)
        override fun `as`(alias: Table<*>): VoteOptionsPath = VoteOptionsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<VoteOptionsRecord, Long?> = super.getIdentity() as Identity<VoteOptionsRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<VoteOptionsRecord> = VOTE_OPTIONS_PKEY
    override fun getReferences(): List<ForeignKey<VoteOptionsRecord, *>> = listOf(VOTE_OPTIONS__VOTE_OPTIONS_VOTE_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.votes</code> table.
     */
    fun votes(): VotesPath = votes
    val votes: VotesPath by lazy { VotesPath(this, VOTE_OPTIONS__VOTE_OPTIONS_VOTE_ID_FKEY, null) }

    private lateinit var _voteSubmissionEntries: VoteSubmissionEntriesPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.vote_submission_entries</code> table
     */
    fun voteSubmissionEntries(): VoteSubmissionEntriesPath {
        if (!this::_voteSubmissionEntries.isInitialized)
            _voteSubmissionEntries = VoteSubmissionEntriesPath(this, null, VOTE_SUBMISSION_ENTRIES__VOTE_SUBMISSION_ENTRIES_OPTION_ID_FKEY.inverseKey)

        return _voteSubmissionEntries;
    }

    val voteSubmissionEntries: VoteSubmissionEntriesPath
        get(): VoteSubmissionEntriesPath = voteSubmissionEntries()

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.vote_submissions</code> table
     */
    val voteSubmissions: VoteSubmissionsPath
        get(): VoteSubmissionsPath = voteSubmissionEntries().voteSubmissions()
    override fun `as`(alias: String): VoteOptions = VoteOptions(DSL.name(alias), this)
    override fun `as`(alias: Name): VoteOptions = VoteOptions(alias, this)
    override fun `as`(alias: Table<*>): VoteOptions = VoteOptions(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): VoteOptions = VoteOptions(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): VoteOptions = VoteOptions(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): VoteOptions = VoteOptions(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): VoteOptions = VoteOptions(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): VoteOptions = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): VoteOptions = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): VoteOptions = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): VoteOptions = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): VoteOptions = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): VoteOptions = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): VoteOptions = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): VoteOptions = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): VoteOptions = where(DSL.notExists(select))
}
