@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package er.codes.saltyvote.jooq.keys


import er.codes.saltyvote.jooq.tables.History
import er.codes.saltyvote.jooq.tables.Users
import er.codes.saltyvote.jooq.tables.records.HistoryRecord
import er.codes.saltyvote.jooq.tables.records.UsersRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.QOM.ForeignKeyRule



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val HISTORY_PKEY: UniqueKey<HistoryRecord> = Internal.createUniqueKey(History.HISTORY, DSL.name("history_pkey"), arrayOf(History.HISTORY.ID), true)
val UQ_USERS_EMAIL: UniqueKey<UsersRecord> = Internal.createUniqueKey(Users.USERS, DSL.name("uq_users_email"), arrayOf(Users.USERS.EMAIL), true)
val UQ_USERS_USERNAME: UniqueKey<UsersRecord> = Internal.createUniqueKey(Users.USERS, DSL.name("uq_users_username"), arrayOf(Users.USERS.USERNAME), true)
val USERS_PKEY: UniqueKey<UsersRecord> = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), arrayOf(Users.USERS.UUID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val HISTORY__HISTORY_USER_ID_FKEY: ForeignKey<HistoryRecord, UsersRecord> = Internal.createForeignKey(History.HISTORY, DSL.name("history_user_id_fkey"), arrayOf(History.HISTORY.USER_ID), er.codes.saltyvote.jooq.keys.USERS_PKEY, arrayOf(Users.USERS.UUID), true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION)
